---
- name: Login into single Registry
  include_tasks: registrylogin.yml
  when: 
    - registry_hostname is defined
    - docker_registries is undefined

- name: Login into Multiple Registries
  include_tasks: registrylogin.yml
  loop: "{{ docker_registries if docker_registries is defined else [] }}"
  loop_control:
    loop_var: registry_item
  vars:
    registry_hostname: "{{ registry_item.registry_hostname }}"
    registry_user_email: "{{ registry_item.registry_user_email }}"
    registry_user_passwd: "{{ registry_item.registry_user_passwd }}"
  when: 
    - docker_registries is defined